wishlistFinFin/list/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin

# from django.urls import path
# from list.views import index, bookdetails_view
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns #image
# Each URL is connected to an HTML response
app_name = 'list'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'list/add/$', views.WishListCreate.as_view(), name='wishlist-add'),

    url(r'list/(?P<pk>[0-9]+)/delete/$', views.WishListDelete.as_view(), name='wishlist-delete'),

    url(r'^(?P<wishlist_id>[0-9]+)/create_book/$', views.create_book, name='create_book'),

    url(r'^(?P<wishlist_id>[0-9]+)/delete_book/(?P<book_id>[0-9]+)/$', views.delete_book, name='delete_book'),

    url(r'bookdetails/$', views.index, name='bookdetails'),

    url(r'shoppingcart$', views.shoppingcart, name='shoppingcart'),

    url(r'removesc/', views.removesc, name='removesc'),  # remove shoppingcart

    url(r'removesfl/', views.removesfl, name='removesfl'),  # remove saved for later

    url(r'saveforlater/$', views.saveforlater, name='saveforlater'),  # save for later from cart

    url(r'addtocart/$', views.addtocart, name='addtocart'),  # add to cart from SFL

    url(r'changequantity/$', views.changequantity, name='changequantity'),

    url(r'addtocart2/$', views.addtocart2, name='addtocart2'),  # add to cart from bookdetails
\
    url(r'addComment/$', views.addComment, name='addComment'),

    url(r'deleteComment/<str:user_id>/$', views.deleteComment, name='deleteComment'),

    url(r'helpful/<str:user_id>/$', views.helpful, name='helpful'),

]

wishlistFinFin/wishlist/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from list import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^list/', include('list.urls')),
    url(r'addComment/$', views.addComment, name='addComment'),
    url(r'deleteComment/(?P<user_id>[\w\-]+)/$', views.deleteComment, name='deleteComment'),
    url(r'^helpful/(?P<user_id>[\w\-]+)/$', views.helpful, name='helpful'),
]

wishlistFinFin/list/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings


# Make sure to sync up with database after adding attributes
# python manage.py makemigrations list
# then python manage.py migrate
class WishList(models.Model):
    wishlist_title = models.CharField(max_length=250)

    def get_absolute_url(self):
        return reverse('list:index')

    def __str__(self):
        return self.wishlist_title


class Book(models.Model):
    wishlist = models.ForeignKey(WishList, on_delete=models.CASCADE)
    book_title = models.CharField(max_length=250)

    def __str__(self):
        return self.book_title


class BookDetails(models.Model):
    author = models.CharField(max_length=200)
    authorbio = models.CharField(max_length=200)
    authorhyperlink = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    genre = models.CharField(max_length=200)
    publisherinfo = models.CharField(max_length=200)
    coverphotourl = models.CharField(max_length=1000,
                                     default='https://upload.wikimedia.org/wikipedia/commons/b/b9/No_Cover.jpg')
    price = models.DecimalField(max_digits=6, decimal_places=2, default=9.99)



class Product(models.Model):
    title = models.CharField(max_length=250)
    author = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    cover = models.CharField(max_length=1000,
                             default='https://upload.wikimedia.org/wikipedia/commons/b/b9/No_Cover.jpg')

    def __unicode__(self):
        return unicode(self.pk)


class Cart(models.Model):
    userId = models.IntegerField()


class CartItems(models.Model):
    cartId = models.ForeignKey(Cart, on_delete=models.CASCADE)
    productId = models.ForeignKey(BookDetails, on_delete=models.CASCADE)
    quantity = models.IntegerField()


class SavedForLater(models.Model):
    cartId = models.ForeignKey(Cart, on_delete=models.CASCADE)
    productId = models.ForeignKey(BookDetails, on_delete=models.CASCADE)

# ANDY
class Comment_and_Rating(models.Model):
	username = models.CharField(max_length=20, primary_key=True, blank=True, null=False)
	content = models.TextField(db_column='User_Comment', blank=True, null=True)
	rating = models.IntegerField(db_column='User_Rating', blank=True, null=True)
	pub_date = models.DateField(db_column='Date_Posted', blank=True, null=True)
	valued = models.IntegerField(db_column='Helpfulness', blank=True, null=True)

# wishlistname = WishList.objects.get(pk=1)
# wishlistname.book_set.all() reveals the set of books within the wishlist
# Create new books with wishlistname.book_set.create(set all attributes here)

wishlistFinFin/list/forms.py
from django import forms

from .models import WishList, Book, BookDetails, CartItems, Product, SavedForLater


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['book_title']

wishlistFinFin/list/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, get_object_or_404
from .forms import BookForm
from .models import WishList, Book, BookDetails, CartItems, Product, SavedForLater, Cart
from django.shortcuts import render, HttpResponse, redirect
from django.http import HttpResponse
from django.template import loader
from django.db.models import Sum, F, Value
# ANDY
from django.db import models
from django.shortcuts import render
from django.db.models import Avg, Count
from django.http import HttpResponseRedirect
from .models import Comment_and_Rating
from datetime import date
import random


class IndexView(generic.ListView):
    template_name = 'list/index.html'

    def get_queryset(self):
        return WishList.objects.all()


class DetailView(generic.DetailView):
    model = WishList
    template_name = 'list/detail.html'


class WishListCreate(CreateView):
    model = WishList
    fields = ['wishlist_title']


class WishListDelete(DeleteView):
    model = WishList
    success_url = reverse_lazy('list:index')


def create_book(request, wishlist_id):
    form = BookForm(request.POST or None, request.FILES or None)
    wishlist = get_object_or_404(WishList, pk=wishlist_id)
    if form.is_valid():
        wishlist_books = wishlist.book_set.all()
        for b in wishlist_books:
            if b.book_title == form.cleaned_data.get("book_title"):
                context = {
                    'wishlist': wishlist,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, 'list/create_book.html', context)
        book = form.save(commit=False)
        book.wishlist = wishlist
        book.save()
        return render(request, 'list/detail.html', {'wishlist': wishlist})
    context = {
        'wishlist': wishlist,
        'form': form,
    }
    return render(request, 'list/create_book.html', context)


def delete_book(request, wishlist_id, book_id):
    wishlist = get_object_or_404(WishList, pk=wishlist_id)
    song = Book.objects.get(pk=book_id)
    song.delete()
    return render(request, 'list/detail.html', {'wishlist': wishlist})


def index(request):
    all_bookdetails = BookDetails.objects.all()
    template = loader.get_template('list/bookdetails.html')

    info = Comment_and_Rating.objects.all()
    info = info.order_by('-valued', '-pub_date')
    avg = Comment_and_Rating.objects.aggregate(Avg('rating'))
    count = Comment_and_Rating.objects.count()
    average = 0
    if count != 0: average = round((avg.pop('rating__avg')), 2)

    context = {
        'all_bookdetails': all_bookdetails,
        'info': info,
        'average': average,
        'count': count,
    }
    return render(request, 'list/bookdetails.html', context)


# return HttpResponse(template.render(context,request)

def shoppingcart(request):
    all_items = CartItems.objects.filter(cartId=1)  # showing information of Cart #1
    totalItems = list(all_items.aggregate(Sum('quantity')).values())[0]
    primary = all_items.values_list('productId', flat=True)
    total = BookDetails.objects.filter(pk__in=primary).aggregate(
        total=Sum(F('price') * F('cartitems__quantity'),
                  output_field=models.FloatField()))['total']
    saved_items = SavedForLater.objects.filter(cartId=1)
    totalsaveditems = saved_items.count()
    context = {'all_items': all_items,
               'totalItems': totalItems,
               'total': total,
               'saved_items': saved_items,
               'totalsaveditems': totalsaveditems,
               }

    return render(request, 'list/shoppingcart.html', context)


def removesc(request):  # shoppingcart remove
    item = CartItems.objects.get(pk=request.POST['item'])
    item.delete()
    return redirect('list/shoppingcart')


def removesfl(request):  # saved for later remove
    item = SavedForLater.objects.get(pk=request.POST['item'])
    item.delete()
    return redirect('list/shoppingcart')


def saveforlater(request):  # removes item from shopping cart and adds it to saved for later
    item = CartItems.objects.get(pk=request.POST['item'])
    b = SavedForLater(cartId=item.cartId, productId=item.productId)
    b.save()
    item.delete()
    return redirect('list/shoppingcart')


def addtocart(request):  # removes item from Saved for later and adds it to shopping cart
    item = SavedForLater.objects.get(pk=request.POST['item'])
    b = CartItems(cartId=item.cartId, productId=item.productId, quantity=1)
    b.save()
    item.delete()
    return redirect('list/shoppingcart')


def changequantity(request):  # removes item from Saved for later and adds it to shopping cart
    item = CartItems.objects.get(pk=request.POST['item'])
    item.quantity = request.POST['quantity']
    item.save()
    return redirect('list/shoppingcart')


def addtocart2(request):  # removes item from Saved for later and adds it to shopping cart
    selected_book = BookDetails.objects.get(pk=request.POST['item'])
    b = CartItems(cartId=Cart.objects.get(pk=1), productId=selected_book, quantity=1)
    b.save()
    return redirect('list/shoppingcart')

# this is used when a new comment is made and posted
def addComment(request):

    input = request.POST.get('ano', False)
    if (input):
        user = "Anonymous"
    else:
        user = "Testing" + str(random.randint(1,100))

    new_comment = Comment_and_Rating(username=user,
                                     content=request.POST['content'],
                                     rating=request.POST['star_value'],
                                     pub_date=date.today(),
                                     valued=0)
    new_comment.save()
    template = loader.get_template('list/bookdetails.html')
    return redirect ('list/bookdetails')


# Here we can delete the comments
def deleteComment(request, user_id):
    commet_to_delete = Comment_and_Rating.objects.get(username=user_id)
    commet_to_delete.delete()
    return render(request, 'list/bookdetails.html')


# This is for "upvoting" a comment
def helpful(request, user_id):
    new_value = Comment_and_Rating.objects.get(username=user_id)
    new_value.valued += 1
    new_value.save()
    return render(request, 'list/bookdetails.html')

wishlistFinFin/list/templates/list/base.html
{% load staticfiles %}
<link rel=stylesheet" type="text/css" href="{% static 'list/style.css' %}"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wishlists</title>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!--Logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'list:bookdetails' %}">
                Books
            </a>
            <a class="navbar-brand" href="{% url 'list:shoppingcart' %}">
                Cart
            </a>
            <a class="navbar-brand" href="{% url 'list:index' %}">
                Wishlists
            </a>
        </div>

        <!-- items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                <!--
               {% for wishlist in object_list %}
               <li class="">
                   <a href="{% url 'list:detail' wishlist.id %}">
                       <span aria-hidden="true"></span>&nbsp; {{wishlist.wishlist_title}}
                   </a>
               </li>
                {% endfor %}
                -->

            </ul>


        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

wishlistFinFin/list/templates/list/bookdetails.html
{% extends 'list/base.html' %}


{% block body %}



    {% for bookdetails in all_bookdetails %}
        <H1 style="font-family:verdana; color:navy;text-align:center">{{ bookdetails.title }}</H1>
        <H3 style="font-family:verdana;text-align:center">{{ bookdetails.title }}</H3>
        <br>
        <div style="width:100%;text-align:center;">
            <a href="https://www.thriftbooks.com/a/harper-lee/198949/">{{ bookdetails.author }}</a>
            <br><br>

            <!-- PHOTO DISPLAY-->

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="bootstrap.css">
    <script type="text/javascript" src="jquery-1.11.2.js"></script>
    <script type="text/javascript" src="bootstrap.js"></script>
    <style type="text/css">
      .my-img a {
        display: inline-block;
        margin: 10px;
        border: 2px solid #CCC;
      }
      .my-img a:hover {
        border: 2px solid #45AFFF;
      }
      .modal-lg {
        width: 30%;
      }
      .modal-body {
        overflow: auto;
        max-height: auto;
      }
    </style>
</head>
<body>

<div class="container">

  <!-- Trigger the modal with a button -->
  <div class="row">
    <div class="col-xs-12 my-img">
      <a href="#" id="link1" data-toggle="modal" data-target="#myModal">
        <img src="{{bookdetails.coverphotourl}}" id="img1" class="img-responsive" width="200px">
      </a>

  </div>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body" id="showImg">

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

</div>
<script type="text/javascript">
      $(document).ready(function() {
        $('img').on('click', function() {
          $("#showImg").empty();
          var image = $(this).attr("src");
          $("#showImg").append("<img class='img-responsive' src='" + image + "' />")
          //alert(image);
        })
      });
</script>

</body>
           <p style="font-family:verdana;text-align:center">{{ bookdetails.authorbio }}</p>
        <p style="font-family:verdana;text-align:center">{{ bookdetails.description }}</p>
        <p style="font-family:verdana;text-align:center">{{ bookdetails.genre }}</p>
        <p style="font-family:verdana;text-align:center">{{ bookdetails.publisherinfo }}</p>
        <p style="font-family:verdana;text-align:center">Rating system:</p>
        <form style="text-align:center" action="{% url 'list:addtocart2' %}" method="POST">
            {% csrf_token %}
            <button name="item" value="{{ bookdetails.pk }}"> Add to Cart</button>
        </form>
        <!--<p style="font-family:verdana;text-align:center"><a href="{% url 'list:addtocart2' %}">Add to cart </a></p>-->
        <p style="font-family:verdana;text-align:center"><a href="{% url 'list:index' %}">Add to wishlist </a></p>

        <h3>Customer reviews</h3>

        Average: {{average}} from {% if count == 1 %} {{count}} Rating {% else %} {{count}} Ratings {% endif %}

        <!-- This area is for displaying all the comments -->
        <ul style="list-style-type:none;">

            {% for content in info %}

                <li>

                <strong> {{content.username}} 	</strong>
                <li> Rating: {{content.rating}} </li>
                <li> {{content.pub_date}} 		</li>
                <li> {{content.content}} 		</li>

                <li> Helpful: {{content.valued}}  		</li>
                <form action="/helpful/{{content.username}}/"
                style="display:inline"
                method="post">{% csrf_token %}
                <input type = "submit" value="Helpful!"/>
                </form>

                <form action="/deleteComment/{{content.username}}/"
                style="display"
                method="post">{% csrf_token %}
                <input type="submit" value="Delete"/>
                </form>

                </li>

            {% endfor %}
        </ul>

        <form action="list/addComment/" method="post"> {% csrf_token %}
            <textarea name="content" style="height:200;width:385px;font-size:12pt;margin:10px;border:2px dashed #4169e1;padding:5px;word-wrap:break-word;" contenteditable="true" spellcheck="true"></textarea><br>
            <input type="radio" name="star_value" value=1> 1
            <input type="radio" name="star_value" value=2> 2
            <input type="radio" name="star_value" value=3> 3
            <input type="radio" name="star_value" value=4> 4
            <input type="radio" name="star_value" value=5 required> 5
            <input type="checkbox" name="ano" value="Anony"> Anonymous
            <input type="submit" value="Submit"/>
        </form>
        </body>
        </html>
        <!-- End of the comment/rating area -->


    {% endfor %}

    <!-- This is for the comment/rating area -->
<html>
<body>
{% endblock %}

wishlistFinFin/list/templates/list/cart.html
<form action="{% url 'remove' %}" method="POST">
    {% csrf_token %}
    {% for item in all_items %}
        <button type="submit" id="item{{ forloop.counter }}" name="item" value="{{ item.pk }}"> BUTTON</button>
        <label for="item{{ forloop.counter }}">
            {{ item.productId }}
        </label><br>
    {% endfor %}
</form>

wishlistFinFin/list/templates/list/create_book.html
{% extends 'list/base.html' %}
{% block body %}

    </h1>

    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="wishlist" value="{{ wishlist }}">
        {% include 'list/form-template.html' %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>

{% endblock %}

wishlistFinFin/list/templates/list/detail.html
{% extends 'list/base.html' %}

{% block body %}

    <h1>{{ wishlist.wishlist_title }}</h1>
    <div>
        <a href="{% url 'list:create_book' wishlist.id %}">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add new book
        </a>
    </div>
    {% for book in wishlist.book_set.all %}
        <form action="{% url 'list:delete_book' wishlist.id book.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <input type="hidden" name="book_id" value="{{ book.id }}"/>
            <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-trash"></span>&nbsp; Delete
            </button>
        </form>
        {{ book.book_title }}
        <br>
    {% endfor %}


{% endblock %}

wishlistFinFin/list/templates/list/form-template.html
{% for field in form %}
    <div class="form-group">
        <label class="control-label col-sm-2">
            {{ field.label_tag }}
        </label>
        <div class="col-sm-10">
            {{ field }}
        </div>
    </div>
{% endfor %}

wishlistFinFin/list/templates/list/index.html
{% extends 'list/base.html' %}

{% block body %}


    <li class="">
        <a href="{% url 'list:wishlist-add' %}">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Wishlist
        </a>
    </li>
    <ul>
        {% for wishlist in object_list %}
            <ul>
                <a href="{% url 'list:detail' wishlist.id %}">{{ wishlist.wishlist_title }}</a>
                <form action="{% url 'list:wishlist-delete' wishlist.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="wishlist_id" value="{{ wishlist.id }}"/>
                    <button type="submit" class="top-menu pull-left" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>

                </form>
            </ul>


        {% endfor %}
    </ul>

{% endblock %}

wishlistFinFin/list/templates/list/shoppingcart.html
{% extends 'list/base.html' %}
<!-- loop begin -->
{% block body %}

    <head>
        <title>Shopping Cart</title>

        <style type="text/css">
            body {
                background-color: azure
            }

            .container {
                width: 80%;
                margin: auto;
            }

            table {
                table-layout: fixed;
                width: 100%;
                border-collapse: collapse;
            }

            tr:hover {
                background-color: #f5f5f5;
            }

            td, th {
                padding: 15px;
                text-align: center;
                vertical-align: top;
                border-bottom: 2px solid #ddd;

            }

            img {
                object-fit: contain;
                width: 200px;
                height: 150px;
            }

            .Checkout {
                background-color: coral;
                border: 2px solid black;
                color: black;
                padding: 15px 32px;
                text-align: center;
                font-size: 16px;
                cursor: pointer;
                float: right;
            }

            hr {
                border-top: 2px solid #ddd;
                margin-top: 6em;
            }

            .link_button {
                background: none !important;
                color: blue;
                border: none;
                padding: 0 !important;
                font: inherit;
                /*border is optional*/
                border-bottom: 1px solid blue;
                cursor: pointer;
            }

        </style>
    </head>
    <body>
    <div class="container">
        <table class="scart">
            <thead>
            <tr>
                <th> Shopping Cart</th>
                <th></th>
                <th>Price</th>
                <th>Quantity</th>

            </tr>
            </thead>
            <tbody>
            {% for item in all_items %}
                <tr>
                    <td>
                        <img src="{{ item.productId.coverphotourl }}" alt="{{ item.productId.title }}">
                    </td>
                    <td>
                        <p>
                        <ul>
                            <b>{{ item.productId.title }}</b>
                            <br><br><br>
                            {{ item.productId.author }}

                        </ul>
                        </p>
                    </td>
                    <td>
                        ${{ item.productId.price }} <br><br><br><br><br><br><br>
                        <form action="{% url 'list:removesc' %}" method="POST">
                            {% csrf_token %}
                            <button class="link_button" name="item" value="{{ item.pk }}"> remove</button>
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'list:changequantity' %}" method="POST">
                            {% csrf_token %}
                            <input type="number" name="quantity" min="1" max="10" value= {{ item.quantity }}>
                            <button name="item" value="{{ item.pk }}"> save</button>
                        </form>
                        <br><br><br><br><br><br>
                        <form action="{% url 'list:saveforlater' %}" method="POST">
                            {% csrf_token %}
                            <button class="link_button" name="item" value="{{ item.pk }}"> Save for Later</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <h2 align="right">Subtotal ({{ totalItems }} item(s)) : ${{ total }}</h2>
        <button class="Checkout">Checkout>></button>
        <hr>

        <table>
            <thead>
            <tr>
                <th>Saved for Later ({{ totalsaveditems }} items(s))</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for item in saved_items %}
                <tr>
                    <td>
                        <a><img src="{{ item.productId.coverphotourl }}" border="0"
                                alt="{{ item.productId.title }}"></a>
                    </td>
                    <td>
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                        Quam quis voluptates nam cumque? Deserunt dolorum magnam nam maiores neque voluptatem,
                        dolores est pariatur, sunt iusto quos iste consequatur sint officia!
                    </td>
                    <td>
                        ${{ item.productId.price }}<br><br><br><br><br><br><br>
                        <form action="{% url 'list:removesfl' %}" method="POST">
                            {% csrf_token %}
                            <button class="link_button" name="item" value="{{ item.pk }}"> remove</button>
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'list:addtocart' %}" method="POST">
                            {% csrf_token %}
                            <button class="link_button" name="item" value="{{ item.pk }}"> Add to Cart</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    </body>
{% endblock %}

wishlistFinFin/list/templates/list/wishlist_form.html
{% extends 'list/base.html' %}
{% block body %}
    <div class="" container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post">
                        {% csrf_token %}
                        {% include 'list/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">
                                    Submit
                                </button>
                            </div>

                        </div>

                    </form>
                </div>
            </div>
        </div>

    </div>
    </div>
{% endblock %}